aira/urls.py
from django.urls import path
from django.views.generic import RedirectView

from aira import views

urlpatterns = [
    path("", views.FrontPageView.as_view(), name="welcome"),
    path("home/<str:username>/", views.AgrifieldListView.as_view(), name="home"),
    path("home/", views.AgrifieldListView.as_view(), name="home"),
    # Recommendation
    path(
        "advice/<int:pk>/",
        RedirectView.as_view(permanent=True, pattern_name="recommendation"),
    ),
    path(
        "recommendation/<int:pk>/",
        views.RecommendationView.as_view(),
        name="recommendation",
    ),
    # Profile
    path(
        "update_profile/<int:pk>/",
        views.UpdateProfileView.as_view(),
        name="update_profile",
    ),
    path("delete_user/<int:pk>/", views.DeleteUserView.as_view(), name="delete_user"),
    # Agrifield
    path(
        "create_agrifield/<str:username>/",
        views.CreateAgrifieldView.as_view(),
        name="create_agrifield",
    ),
    path(
        "update_agrifield/<int:pk>/",
        views.UpdateAgrifieldView.as_view(),
        name="update_agrifield",
    ),
    path(
        "delete_agrifield/<int:pk>/",
        views.DeleteAgrifieldView.as_view(),
        name="delete_agrifield",
    ),
    path(
        "agrifield/<int:agrifield_id>/timeseries/<str:variable>/",
        views.AgrifieldTimeseriesView.as_view(),
        name="agrifield-timeseries",
    ),
    path(
        "agrifield/<int:agrifield_id>/soil_analysis/",
        views.DownloadSoilAnalysisView.as_view(),
        name="agrifield-soil-analysis",
    ),
    path(
        "create_irrigationlog/<int:pk>/",
        views.CreateAppliedIrrigationView.as_view(),
        name="create_irrlog",
    ),
    path(
        "update_irrigationlog/<int:pk>/",
        views.UpdateAppliedIrrigationView.as_view(),
        name="update_irrlog",
    ),
    path(
        "delete_irrigationlog/<int:pk>/",
        views.DeleteAppliedIrrigationView.as_view(),
        name="delete_irrlog",
    ),
    path("conversion_tools/", views.ConversionToolsView.as_view(), name="tools"),
    path("try/", views.DemoView.as_view(), name="try"),
    path(
        "irrigation-performance-chart/<int:pk>/",
        views.IrrigationPerformanceView.as_view(),
        name="irrigation-chart",
    ),
    path(
        "download-irrigation-performance/<int:pk>/",
        views.performance_csv,
        name="performance_csv",
    ),
    path(
        "supervised_user/remove/",
        views.remove_supervised_user_from_user_list,
        name="supervised_user_remove",
    ),
]

aira/models.py
import csv
import datetime as dt
import math
import os
from collections import OrderedDict
from glob import iglob
from io import StringIO

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.core.cache import cache
from django.core.files.storage import FileSystemStorage
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import Http404
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

import swb
from hspatial import PointTimeseries, extract_point_from_raster
from osgeo import gdal

from .agrifield import AgrifieldSWBMixin, AgrifieldSWBResultsMixin

# notification_options is the list of options the user can select for
# notifications, e.g. be notified every day, every two days, every week, and so
# on. It is a dictionary; the key is an id of the option, and the value is a
# tuple whose first element is the human-readable description of an option,
# and the second element is a function receiving a single argument (normally
# the current date) and returning True if notifications are due in that
# particular date.

notification_options = OrderedDict(
    (
        ("D", (_("Daily"), lambda x: True)),
        ("2D", (_("Every two days"), lambda x: x.toordinal() % 2 == 0)),
        ("3D", (_("Every three days"), lambda x: x.toordinal() % 3 == 0)),
        ("4D", (_("Every four days"), lambda x: x.toordinal() % 4 == 0)),
        ("5D", (_("Every five days"), lambda x: x.toordinal() % 5 == 0)),
        ("7D", (_("Weekly"), lambda x: x.weekday() == 0)),
        ("10D", (_("Every ten days"), lambda x: x.day in (1, 11, 21))),
        ("30D", (_("Monthly"), lambda x: x.day == 1)),
    )
)


YES_OR_NO = ((True, _("Yes")), (False, _("No")))

YES_OR_NO_OR_NULL = ((True, _("Yes")), (False, _("No")), (None, "-"))

EMAIL_LANGUAGE_CHOICES = (("en", "English"), ("el", "Ελληνικά"))


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True)
    notification = models.CharField(
        max_length=3,
        blank=True,
        default="",
        choices=[(x, notification_options[x][0]) for x in notification_options],
    )
    email_language = models.CharField(
        max_length=3,
        default=EMAIL_LANGUAGE_CHOICES[0][0],
        choices=EMAIL_LANGUAGE_CHOICES,
    )
    supervisor = models.ForeignKey(
        User, related_name="supervisor", null=True, blank=True, on_delete=models.CASCADE
    )
    supervision_question = models.BooleanField(choices=YES_OR_NO, default=False)

    class Meta:
        verbose_name_plural = "Profiles"

    def get_supervised(self):
        return Profile.objects.filter(supervisor=self.user)

    def __str__(self):
        return "UserProfile: {}".format(self.user)


@receiver(post_save, sender=User)
def create__or_update_user_profile(sender, instance, created, **kwargs):
    if not Profile.objects.filter(user=instance).exists():
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()


class CropType(models.Model):
    name = models.CharField(max_length=100)
    root_depth_max = models.FloatField()
    root_depth_min = models.FloatField()
    max_allowed_depletion = models.FloatField()
    kc_plantingdate = models.FloatField()
    kc_offseason = models.FloatField(verbose_name="Kc off-season")
    planting_date = models.DateField()
    fek_category = models.IntegerField()

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Crop Types"

    def __str__(self):
        return str(self.name)

    @property
    def most_recent_planting_date(self):
        today = dt.date.today()
        result = self.planting_date.replace(year=today.year)
        if result <= today:
            return result
        return result.replace(year=today.year - 1)

    @property
    def kc_stages(self):
        result = []
        for kc_stage in self.croptypekcstage_set.order_by("order"):
            result.append(swb.KcStage(kc_stage.ndays, kc_stage.kc_end))
        return result

    @property
    def kc_stages_str(self):
        kc_stages = self.croptypekcstage_set.order_by("order")
        lines = [f"{s.ndays}\t{s.kc_end}" for s in kc_stages]
        return "\n".join(lines)


class KcStage(models.Model):
    order = models.PositiveSmallIntegerField()
    ndays = models.PositiveSmallIntegerField()
    kc_end = models.FloatField(
        validators=[MaxValueValidator(1.50), MinValueValidator(0.10)]
    )

    class Meta:
        abstract = True


class CropTypeKcStage(KcStage):
    crop_type = models.ForeignKey(CropType, on_delete=models.CASCADE)


class IrrigationType(models.Model):
    name = models.CharField(max_length=100)
    efficiency = models.FloatField()

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Irrigation Types"

    def __str__(self):
        return str(self.name)


class SoilAnalysisStorage(FileSystemStorage):
    def url(self, name):
        agrifield = Agrifield.objects.get(soil_analysis=name)
        return reverse("agrifield-soil-analysis", kwargs={"agrifield_id": agrifield.id})


class Agrifield(models.Model, AgrifieldSWBMixin, AgrifieldSWBResultsMixin):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default="i.e. MyField1")
    is_virtual = models.NullBooleanField(
        choices=YES_OR_NO_OR_NULL, null=True, default=None
    )
    location = models.PointField()
    crop_type = models.ForeignKey(CropType, on_delete=models.CASCADE)
    irrigation_type = models.ForeignKey(IrrigationType, on_delete=models.CASCADE)
    area = models.FloatField()
    use_custom_parameters = models.BooleanField(default=False)
    custom_kc_offseason = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(1.50), MinValueValidator(0.10)],
    )
    custom_kc_plantingdate = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(1.50), MinValueValidator(0.10)],
    )
    custom_planting_date = models.DateField(null=True, blank=True)
    custom_root_depth_max = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(4.00), MinValueValidator(0.20)],
    )
    custom_root_depth_min = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(2.00), MinValueValidator(0.1)],
    )
    custom_max_allowed_depletion = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(0.99), MinValueValidator(0.00)],
    )
    custom_efficiency = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(1.00), MinValueValidator(0.05)],
    )
    custom_irrigation_optimizer = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(1.00), MinValueValidator(0.10)],
    )
    custom_field_capacity = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(0.45), MinValueValidator(0.10)],
    )
    custom_thetaS = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(0.55), MinValueValidator(0.30)],
    )
    custom_wilting_point = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(0.22), MinValueValidator(0.00)],
    )
    soil_analysis = models.FileField(
        blank=True, storage=SoilAnalysisStorage(), upload_to="soil_analyses"
    )

    @property
    def wilting_point(self):
        if self.use_custom_parameters and self.custom_wilting_point:
            return self.custom_wilting_point
        else:
            return self.default_wilting_point

    @property
    def default_wilting_point(self):
        if not self.in_covered_area:
            return None
        else:
            return extract_point_from_raster(
                self.location,
                gdal.Open(os.path.join(settings.AIRA_DATA_SOIL, "pwp.tif")),
            )

    @property
    def theta_s(self):
        if self.use_custom_parameters and self.custom_thetaS:
            return self.custom_thetaS
        else:
            return self.default_theta_s

    @property
    def default_theta_s(self):
        if not self.in_covered_area:
            return None
        else:
            return extract_point_from_raster(
                self.location,
                gdal.Open(os.path.join(settings.AIRA_DATA_SOIL, "theta_s.tif")),
            )

    @property
    def field_capacity(self):
        if self.use_custom_parameters and self.custom_field_capacity:
            return self.custom_field_capacity
        else:
            return self.default_field_capacity

    @property
    def default_field_capacity(self):
        if not self.in_covered_area:
            return None
        else:
            return extract_point_from_raster(
                self.location,
                gdal.Open(os.path.join(settings.AIRA_DATA_SOIL, "fc.tif")),
            )

    @property
    def irrigation_efficiency(self):
        if self.use_custom_parameters and self.custom_efficiency:
            return self.custom_efficiency
        else:
            return self.irrigation_type.efficiency

    @property
    def p(self):
        if self.use_custom_parameters and self.custom_max_allowed_depletion:
            return self.custom_max_allowed_depletion
        else:
            return self.crop_type.max_allowed_depletion

    @property
    def root_depth_max(self):
        if self.use_custom_parameters and self.custom_root_depth_max:
            return self.custom_root_depth_max
        else:

aira/templates/aira/advice.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
{% load mathfilters %}

{% block title %} {{ object.name }} | {% trans "Report" %}{% endblock %}
{% block content %}
{% if user.username == "demo" %}
 <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <i class="fa fa-info-circle fa-2x"></i>&nbsp; <span style="font-size:32px">{% trans "demo" %}</span>
</div>
{% endif %}
<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <b>{% trans "Field Name" %}:</b> <a href="{% url 'update_agrifield' object.id %}">{{ object.name }}</a>
      </div>
      <div class="panel-body">
        <div id="field_map" class="map"></div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <b>{% trans "Crop Type" %}:</b> <a href="{% url 'update_agrifield' object.id %}">{{ object.crop_type.name }}</a>
              {% if object.use_custom_parameters %}
                    {% trans "using custom parameters" %}
              {% endif %}
          </div>
          <div class="panel-body">
            <b>{% trans "Estimated root depth (max)" %}:</b> {{ object.root_depth }} m <br>
            <b>{% trans "Maximum Allowable Depletion" %}:</b> {{ object.p|mul:100|floatformat:"1" }}%<br>
            <b>{% trans "Field Capacity" %}:</b> {{ object.field_capacity|mul:100|floatformat:"1"}}%<br>
            <b>{% trans "Soil moisture at saturation" %} (Θ<sub>s</sub>):</b> {{ object.theta_s |mul:100|floatformat:"1" }}%<br>
            <b>{% trans "Permanent Wilting Point" %}:</b> {{ object.wilting_point|mul:100|floatformat:"1"  }}% <br>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <b>{% trans "Irrigation System Type" %}: </b><a href="{% url 'update_agrifield' object.id %}">{{ object.irrigation_type.name }}</a>
            {% if object.use_custom_parameters %}
                   {% trans "using custom parameters" %}
            {% endif %}
          </div>
          <div class="panel-body">
            <b>{% trans "Irrigation efficiency factor" %}:</b> {{ object.irrigation_efficiency }} <br>
            <b>{% trans "Irrigation Optimizer" %}:</b> {{ object.irrigation_optimizer }} <br>
            {% if object.last_irrigation %}
              <b>{% trans "Last recorded irrigation" %}:</b> {{ object.last_irrigation.time|date:"d/m/Y H:00" }} <br>
              <b>{% trans "Applied water" %} (m³):</b> {{ object.last_irrigation.applied_water|floatformat:"1"  }} {% if object.last_irrigation.message %}({{ object.last_irrigation.message }}){% endif %}<br>
            {% else %}
               <b>{% trans "Last recorded irrigation" %}:</b> {% trans "None" %} <br>
               <b>{% trans "Applied water" %} m³: </b>{% trans "None" %}
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- row -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
            {% if object.status != 'done' %}
                <p class="alert alert-warning">{% trans "This field is being (re)calculated. Reload the page some time later to view the updated results. The calculation usually takes from a few seconds to a few minutes." %}</p>
            {% endif %}
            {% if object.results %}
                {% trans "Detailed Calculations for" %}
                {% trans "Forecast Period" %}: <span class="text-warning">{{ object.results.sdh|date:"d/m/Y" }}</span> {% trans "to" %} <span class="text-warning">{{ object.results.edh|date:"d/m/Y" }}</span>
                <div id="results" class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th align="left">{% trans "Date" %}<br> </th>
                            <th align="left">{% trans "Effective Precipitation" %} <br>(mm)</th>
                            <th align="left">{% trans "Depletion" %} <br> (mm)</th>
                            <th align="left">{% trans "Soil moisture" %} <br>(%)</th>
                            <th align="left">{% trans "Irrigate" %} ?</th>
                            <th align="left">
                                {% blocktrans %}
                                  Water stress <br> factor
                                {% endblocktrans %}
                            </th>
                            <th align="left">{% trans "Irrigation Water Amount" %}<br> (mm)</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for result in object.results.swb_report  %}
                            {% if  result.4 %}
                            <tr class="success">
                            {% else %}
                            <tr class="active">
                            {% endif %}
                                <td align="left">{{ result.0 }}</td>
                                <td align="left">{{ result.1 |floatformat:"0"}}</td>
                                <td align="left">{{ result.2|floatformat:"0"}}</td>
                                <td align="left"> {{ result.3|mul:100|floatformat:"1" }}</td>
                                {% if result.4 %}
                                <td align="left"> {% trans "YES" %}</td>
                                {% else %}
                                <td align="left"> {% trans "NO" %} </td>
                                {% endif %}
                                <td align="left"> {{ result.5|floatformat:"2" }}</td>
                                <td align="left"> {{ result.6|floatformat:"0" }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extrajs %}
         <script type="text/javascript">
          function make_coords(coord) {
              return parseFloat(coord.replace(",","."));
            };
             map = new OpenLayers.Map('field_map',
                   {units: 'm',
                    displayProjection: 'EPSG:4326',
                    controls: [new OpenLayers.Control.LayerSwitcher(),
                               new OpenLayers.Control.Zoom(),
                               new OpenLayers.Control.Navigation(),
                               new OpenLayers.Control.MousePosition(),
                               new OpenLayers.Control.ScaleLine()]
                    });
             // Open Cycle
             var cycle = new OpenLayers.Layer.OSM(
                       "Open Cycle Map",
                       ["https://a.tile.thunderforest.com/cycle/${z}/${x}/${y}.png?" + aira.thunderforestApiKeyQueryElement,
                        "https://b.tile.thunderforest.com/cycle/${z}/${x}/${y}.png?" + aira.thunderforestApiKeyQueryElement,
                        "https://c.tile.thunderforest.com/cycle/${z}/${x}/${y}.png?" + aira.thunderforestApiKeyQueryElement],
                       {isBaseLayer: true,
                        projection: 'EPSG:3857'});

              // Study area
             var kml = new OpenLayers.Layer.Vector("{% trans 'IRMA area' %}",
                       {strategies: [new OpenLayers.Strategy.Fixed()],
                         visibility: true,
                       protocol: new OpenLayers.Protocol.HTTP(
                                {url: "{% static 'kml/study_area.kml' %}",
                                format: new OpenLayers.Format.KML()})})
             var ktimatologio = new OpenLayers.Layer.WMS("Hellenic Cadastre",
                         "http://gis.ktimanet.gr/wms/wmsopen/wmsserver.aspx",
                           {   layers: 'KTBASEMAP', transparent: false},
                           {   isBaseLayer: true,
                                numZoomLevels: 24,
                               projection: new OpenLayers.Projection("EPSG:900913"),
                               iformat: 'image/png'});
             var googleMaps = new OpenLayers.Layer.Google(
                 "Google Satellite", {type: google.maps.MapTypeId.SATELLITE, numZoomLevels: 22}
             );
             map.addLayers([googleMaps, ktimatologio, cycle, kml]);

             var fieldloc = new OpenLayers.LonLat(make_coords("{{ object.location.x }}"), make_coords("{{ object.location.y }}")).transform('EPSG:4326', 'EPSG:3857');
             var marker = new OpenLayers.Marker(fieldloc)
             var markers = new OpenLayers.Layer.Markers( "{{ object.name }}" );
             map.addLayer(markers);
             markers.addMarker(marker);
             map.setCenter(fieldloc, 18);

              $(document).ready(function(){
              $("#show_results").click(function(){
                  $("#results").stop().toggle();
              });
          });
       </script>
{% endblock extrajs %}

aira/templates/aira/agrifield_create.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load aira_extras %}


{% load bootstrap3 %}

{% block title %} {% trans "Add Agrifield" %} - {{user}} {% endblock %}

{% block content %}

{% menu request.user request.resolver_match.kwargs request.resolver_match.url_name %} <br>

{% leaflet_map %}

<hr>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-block">
                <form method="post" role="form" action=".">
                    {% csrf_token %}
                    <div class='col-md-6'>
                        <div class='form-group'>
                            {% bootstrap_field form.name %}
                            {% bootstrap_field form.area %}
                            {% bootstrap_field form.latitude %}
                            {% bootstrap_field form.longitude %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            {% bootstrap_field form.crop_type %}
                            {% bootstrap_field form.irrigation_type %}
                            {% bootstrap_field form.is_virtual%}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success btn-xs">{% trans "Add" %}</button>
                    </div>
                </form>
                {% if object_list %}
                    <button class="btn btn-xs btn-default pull-right" id="manage-agrifields"><i class="fa fa-chevron-down" aria-hidden="true"></i></button>
                    <div class="row">
                        <div class="col-md-12">
                            <div id="agrifields-list-table" class="card-block" {% if not 'page' in request.get_full_path %} style="display:None;"{% endif %}>
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>{% trans "Agrifield" %}</th>
                                            <th>{% trans "Crop Type" %} / {% trans "Irrigation Type" %}</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for agrifield in object_list  %}
                                        <tr>
                                            <td>{% if agrifield.is_virtual %}<span><img  data-toggle="tooltip" title="{% trans 'Virtual Field' %}" style="float:left;padding-right:10px" height="25" width="35" src="{% static 'img/rocket.png' %}" alt=""></span>{% endif %}</td>
                                            <td>{{ agrifield.name }}</td>
                                            <td><span>{{ agrifield.crop_type.name}}<br>{{ agrifield.irrigation_type.name }}</span></td>
                                            <td>
                                                <span style="padding-right:20px;" class="align-middle"><a id="{{ agrifield.pk }}" class="aira-nav-link" href="{% url 'edit-agrifield' agrifield.owner agrifield.slug %}"><i data-toggle="tooltip" title="{% trans 'Edit' %}" class="fa fa-pencil" aria-hidden="true"></i></a></span>
                                                <span style="padding-right:20px;" class="align-middle"><a id="{{ agrifield.pk }}" class="aira-nav-link" href="{% url 'add-irrigationlog' agrifield.slug %}"><i data-toggle="tooltip" title="{% trans 'Irrigation Logs' %}" class="fa fa-list-ol" aria-hidden="true"></i></a></span>
                                                <span style="padding-right:20px;" class="pull-left"><a id="{{ agrifield.pk }}" class="aira-nav-link trash" href="#"><i data-toggle="tooltip" title="{% trans 'Remove' %}" class="fa fa-trash"></i></a></span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <nav aria-label="">
                                    <ul class="pagination justify-content-end">
                                        {% if object_list.has_previous %}
                                            <li class="page-item"><a class="page-link"href="?page={{ object_list.previous_page_number }}">Previous</a></li>
                                        {% endif %}

                                        {% for i in object_list.paginator.page_range %}
                                            <li class="page-item {% if object_list.number == i %}active{% endif %}">
                                                <a class="page-link"href="?page={{i}}">{{i}}</a>
                                            </li>
                                        {% endfor %}

                                        {% if object_list.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ object_list.next_page_number }}">Next</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/aira.js' %}"></script>

<script type="text/javascript">
    // Create a map can capture user click on map to form input lat, long
    aira.LeafletMap.createMap('map',[], [39.15,20.98], 10, true, [], null);

    $(document).ready(function(){
        //TODO: Find a better way
        $('#id_area').attr('placeholder',"m²");
    });

    // Toggle Irrigation log Table
    $(document).on("click", "#manage-agrifields", function(){
        $("#agrifields-list-table").toggle();
        $("i", this).toggleClass("fa fa-chevron-up fa fa-chevron-down");
    });

    // Trash an object with a  conform pop up
    $(document).on("click", ".trash", function(e) {
         var agrifield_id = ($(this).attr('id'));
         var table_row = $(this).closest('tr')
         bootbox.confirm({
             title: "{% trans 'aira message' %}",
             message: "<h3 style='padding-left:70px'>{% trans 'Do you want delete this field?' %}</h3>",
             buttons: {
                 confirm: {
                     label: "{% trans  'Yes' %}",
                     className: 'btn btn-success pull-left'
                 },
                 cancel: {
                     label: "{% trans  'No' %}",
                     className: 'btn btn-danger'
                 }
             },
             callback:function(result){
                if (result) {
                    $.ajax({
                        url : "/delete/agrifield/",
                        type : "POST",
                        data : { agrifield_pk: agrifield_id },
                        success : function(response) {
                             table_row.remove()
                             $.notify("{% trans  'Agrifield deleted' %}");
                        },
                        error : function(xhr,errmsg,err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                    });
                }
            }
         })
    })
</script>
{% endblock %}

aira/templates/aira/irrigationlog_update.html
{% extends 'aira/base/main.html' %}
{% load i18n %}

{% load bootstrap3 %}
{% block title %} {{ user }} {% endblock %}

{% block content %}
{% if user.username == "demo" %}
 <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <i class="fa fa-info-circle fa-2x"></i>&nbsp; <span style="font-size:32px">{% trans "demo" %}</span>
</div>
{% endif %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>{% trans "Update" %} </h3>
      <hr>
      <form method="post" role="form" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons %}
        {% if user.username != "demo" %}
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success btn-xs">{% trans "Update" %}</button>
          <a class="btn btn-success btn-xs" href="{% url 'create_irrlog' agrifield_id %}"> {% trans "Back" %} </a>
        </div>

        {% endif %}
        {% endbuttons %}
      </form>
    </div>
</div>
{% endblock %}
    
{% block extrajs %}
        <script type="text/javascript">
          $("#id_time").datetimepicker({
            format: "yyyy-mm-dd hh:ii",
            autoclose: true,
            todayBtn: true,
            pickerPosition: "bottom-left"
            });
        $(document).ready(function() {
            var label_inner = $("label[for='id_applied_water']").html()
            $("label[for='id_applied_water']").html(label_inner + " (m³)")
        });
      </script>
{% endblock %}